version: "1"

databases:
  - name: worktracker-db
    databaseName: worktracker
    user: worktracker
    plan: free

services:
  - type: web
    name: api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: worktracker-db
          property: connectionString
      - key: CORS_ORIGINS
        value: https://in-office.vercel.app
      - key: ADMIN_SECRET
        generateValue: true
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: SLACK_GENERAL_CHANNEL_ID
        value: "CGHDKEF6J"
      - key: SLACK_SCHEDULER_SECRET
        generateValue: true
      - key: SLACK_TEST_MODE_USER_NAME
        sync: false
